openapi: 3.0.3
info:
  title: User Authentication API
  description: API for user authentication and token management.
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: User login
      description: Handles user login and returns user information, roles, permissions, and authentication tokens. If the user does not exist, a new user will be created.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: The user's email address.
                  format: email
                  example: user@example.com
                password:
                  type: string
                  description: The user's password.
                  format: password
                  example: password123
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates the login was successful.
                    example: true
                  message:
                    type: string
                    description: A message indicating the result of the login.
                    example: Login successful
                  data:
                    type: object
                    description: Contains user information and authentication tokens.
                    properties:
                      user:
                        type: object
                        description: User profile and role information.
                        properties:
                          id:
                            type: string
                            description: The user's unique identifier.
                            example: 8260480d-112a-4e71-87d0-1c0a591edac4
                          username:
                            type: string
                            description: The user's username.
                            example: johndoe
                          email:
                            type: string
                            description: The user's email address.
                            example: user@example.com
                          first_name:
                            type: string
                            description: The user's first name.
                            example: John
                          last_name:
                            type: string
                            description: The user's last name.
                            example: Doe
                          roles:
                            type: array
                            description: A list of roles assigned to the user.
                            items:
                              type: string
                            example: ["Admin", "Editor"]
                          permissions:
                            type: array
                            description: A list of permissions assigned to the user.
                            items:
                              type: string
                            example: ["read:user", "write:post"]
                          service:
                            type: string
                            description: The service associated with the user.
                            example: "attendify"
                      credentials:
                        type: object
                        description: Authentication tokens for the user.
                        properties:
                          accessToken:
                            type: string
                            description: The access token for the user.
                            example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ...
                          refreshToken:
                            type: string
                            description: The refresh token for the user.
                            example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ...
        "400":
          description: Invalid request or failed login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates the request was unsuccessful.
                    example: false
                  message:
                    type: string
                    description: A message explaining the error.
                    example: Invalid request
                  errors:
                    type: array
                    description: List of validation errors or specific issues.
                    items:
                      type: string
                    example:
                      - Email and password are required
                      - Invalid credentials
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates the server encountered an error.
                    example: false
                  message:
                    type: string
                    description: A message indicating the server error.
                    example: An unexpected error occurred
tags:
  - name: Authentication
    description: Endpoints for user authentication and authorization
